### ISSUE TITLE
Error loading games list when live games are on

### ISSUE THREAD

**Issue by ohhmyy** [pigskin/kodi-gamepass#433]
Hi guys. I'm running the matrix version on kodi 19. Everything works quite well so far, except when live games are on. 
When I want to display the list of games of the current preseason week 1, I get an error message when a live game is in progress:
```
ERROR <general>: [script.video.nfl.gamepass] script.video.nfl.gamepass: can't concat str to bytes
                 Traceback (most recent call last):
                   File "/storage/.kodi/addons/script.video.nfl.gamepass/default.py", line 555, in onClick
                     self.display_weeks_games()
                   File "/storage/.kodi/addons/script.video.nfl.gamepass/default.py", line 336, in display_weeks_games
                     game_info += '[CR]» Live «'
                 TypeError: can't concat str to bytes
```

**Comment by marcfuhrmann** [comment]
Replace line 336 with:

game_info += ("[CR]» Live «").encode('utf-8')

**Comment by ohhmyy** [comment]
That worked. Thanks a lot.

**Comment by marcfuhrmann** [comment]
The game that has the focus in the list has 'NONE' as the team`s City/State.

Replace lines 299-304 in default.py with:

game_name_shrt = '[B]%s @ %s[/B]' % (game['visitorNickName'], game['homeNickName'])
game_name_full = '[B]%s[/B]' % (game['video']['title'])

**Comment by marcfuhrmann** [comment]
The "Fix for display of NONE" is only working on past game listings.
So I deleted my fix, because it is not working for future game listings

**Comment by jm-duke** [comment]
Yeah, caught another Python 2 -> Python 3 issue here ;-)

The issue is introduced a few lines up. In theory I have it fixed locally, but I still need to test this.
